# Generated by Django 4.0.3 on 2022-06-19 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('special_equipment', '0002_equipmentmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentunit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='apskaitomam priemonės vienetui suteiktas unikalus inventorinis numeris', primary_key=True, serialize=False, verbose_name='inventorinis numeris'),
        ),
        migrations.AlterField(
            model_name='equipmentunit',
            name='status',
            field=models.CharField(blank=True, choices=[('k', 'sandėlyje/prieinama'), ('p', 'paimta'), ('r', 'remonuotina'), ('n', 'naudojimui netinkama(nurašytina)')], db_index=True, default='k', max_length=1, verbose_name='prieinamumas'),
        ),
    ]
