# Generated by Django 4.0.3 on 2022-06-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_equipment', '0004_equipmentunit_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentunit',
            name='notes',
            field=models.CharField(default=None, max_length=224, null=True, verbose_name='pastabos'),
        ),
        migrations.AlterField(
            model_name='equipmentunit',
            name='status',
            field=models.CharField(blank=True, choices=[('ok', 'sandėlyje/prieinama'), ('p', 'paimta'), ('r', 'remonuotina'), ('n', 'naudojimui netinkama(nurašytina)'), ('kt', 'kitas statusas (priemonė neprieinama)')], db_index=True, default='ok', max_length=2, verbose_name='prieinamumas'),
        ),
    ]
