# Generated by Django 4.0.3 on 2022-06-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_equipment', '0005_equipmentunit_notes_alter_equipmentunit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentunit',
            name='returning_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='perduota iki: '),
        ),
        migrations.AlterField(
            model_name='equipmentunit',
            name='status',
            field=models.CharField(blank=True, choices=[('ok', 'sandėlyje/prieinama'), ('p', 'paimta'), ('r', 'remonuotina'), ('no', 'naudojimui netinkama(nurašytina)'), ('kt', 'kitas statusas (priemonė neprieinama)')], db_index=True, default='ok', max_length=2, verbose_name='prieinamumas'),
        ),
    ]
