# Generated by Django 4.0.3 on 2022-06-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_equipment', '0006_equipmentunit_returning_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentunit',
            name='notes',
            field=models.CharField(default='-', max_length=224, null=True, verbose_name='pastabos'),
        ),
    ]
