# Generated by Django 4.0.3 on 2022-06-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_equipment', '0007_alter_equipmentunit_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='category',
            field=models.ManyToManyField(help_text='nurodykit priemonės kategoriją', related_name='types', to='special_equipment.category', verbose_name='Kategorija'),
        ),
    ]
