# Generated by Django 4.0.3 on 2022-06-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_equipment', '0008_type_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentunit',
            name='category',
        ),
    ]
