# Generated by Django 4.0.3 on 2022-06-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_equipment', '0009_remove_equipmentunit_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.CharField(default='rusies aprasymas nepateiktas', help_text='rusies aprasymas?', max_length=156, verbose_name='aprasymas laikinas'),
        ),
    ]
