# Generated by Django 4.0.3 on 2022-06-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_equipment', '0012_alter_equipmentunit_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentunit',
            name='status',
            field=models.CharField(blank=True, choices=[('ok', 'sandėlyje/prieinama'), ('p', 'paimta'), ('r', 'reservuota'), ('s', 'sugadinta (reikalingas remontas)'), ('no', 'naudojimui netinkama(nurašytina)'), ('kt', 'kitas statusas (priemonė neprieinama)')], db_index=True, default='ok', max_length=2, verbose_name='prieinamumas'),
        ),
    ]
