# Generated by Django 4.0.3 on 2022-06-25 07:47

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('special_equipment', '0013_alter_equipmentunit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmodel',
            name='description',
            field=tinymce.models.HTMLField(default='informacija tikslinama', help_text='svarbiausia informacija apie gaminį', verbose_name='arašymas,pagrindinės modelio savybės'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.CharField(default='-', help_text='keli rūšies pavyzdžiai ir kita svarbiausia informacija', max_length=156, verbose_name='trumpas aprašymas'),
        ),
    ]
