# Generated by Django 4.0.3 on 2022-06-26 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('special_equipment', '0014_alter_equipmentmodel_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentModelComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField(verbose_name='atsiliepimas')),
                ('commentator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_comments', to=settings.AUTH_USER_MODEL, verbose_name='commentator')),
                ('equipment_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_model_comments', to='special_equipment.equipmentmodel', verbose_name='modelis')),
            ],
        ),
    ]
