# Generated by Django 4.0.3 on 2022-06-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_equipment', '0015_equipmentmodelcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentmodelcomment',
            options={'ordering': ['created_at'], 'verbose_name': 'vartotojo komentaras', 'verbose_name_plural': 'vartotojų komentarai'},
        ),
    ]
