# Generated by Django 4.0.3 on 2022-06-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_equipment', '0016_alter_equipmentmodelcomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentunit',
            options={'ordering': ['returning_date'], 'verbose_name': 'spec. priemonės vienetas', 'verbose_name_plural': 'spec. priemonių atsargos'},
        ),
    ]
