# Generated by Django 4.0.3 on 2022-06-27 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('special_equipment', '0017_alter_equipmentunit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmodelcomment',
            name='commentator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_model_comments', to=settings.AUTH_USER_MODEL, verbose_name='commentator'),
        ),
    ]
