# Generated by Django 4.0.3 on 2022-06-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_equipment', '0020_alter_equipmentmodelcomment_commentator'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmodel',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='special_equipment/pics', verbose_name='gaminio foto'),
        ),
    ]
