# Generated by Django 4.0.3 on 2022-06-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_equipment', '0022_alter_equipmentunit_returning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmodel',
            name='description',
            field=models.CharField(default='informacija tikslinama', help_text='svarbiausia informacija apie gaminį', max_length=156, verbose_name='arašymas,pagrindinės modelio savybės'),
        ),
    ]
